version: '3.8'
services:
  todo-app:
    build: ./
    command: ./todo-app
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5436:5432
